import os

os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['OMP_NUM_THREADS'] = '1'

WAIT_TIME = 20
RESULTS_FILE = 'results.xlsx'
SIMILARITY_THRESHOLD = 0.89
MAX_ADDITIONAL_IMAGES = 3
MAX_TOTAL_RECORDS = 2000
MAX_ADDITIONAL_SEARCHES_PER_IMAGE = 2
NUM_PARALLEL_PROCESSES = 4
